# Generated by Django 4.2.15 on 2024-08-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_carouselimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimage",
            name="image",
            field=models.ImageField(upload_to="carousel_images/"),
        ),
    ]
